package ru.steeloscar.gitinfocleanarchitecture.datasource

import ru.steeloscar.gitinfocleanarchitecture.data.repository.api.model.RepositoryCommit
import ru.steeloscar.gitinfocleanarchitecture.domain.entity.RepositoryCommitEntity
import ru.steeloscar.gitinfocleanarchitecture.presentation.model.RepositoryCommitUI

object TestDataSourceRepositoryCommit {

    fun getRepositoryCommits(): ArrayList<RepositoryCommit> {
        return arrayListOf(
            RepositoryCommit(
                "123456789qwerty123456789qwerty1234567890",
                "node_id1",
                RepositoryCommit.Commit(
                    RepositoryCommit.Commit.Author(
                        "name1",
                        "email1",
                        "date1"
                    ),
                    RepositoryCommit.Commit.Author(
                        "name1",
                        "email1",
                        "date1"
                    ),
                    "message1",
                    RepositoryCommit.Commit.Tree(
                        "123456789qwerty123456789qwerty1234567890",
                        "url1"
                    ),
                    "url1",
                    1,
                    RepositoryCommit.Commit.Verification(
                        false,
                        "unsigned",
                        null,
                        null
                    )
                ),
                "url1",
                "html_url1",
                "comments_url1",
                RepositoryCommit.Committer(
                    "login1",
                    1,
                    "node_id1",
                    "avatar_url1",
                    "",
                    "url1",
                    "html_url1",
                    "followers_url1",
                    "following_url1",
                    "gits_url1",
                    "starred_url1",
                    "subscriptions_url1",
                    "organizations_url1",
                    "repos_url1",
                    "events_url1",
                    "received_url1",
                    "type1",
                false
                ),
                RepositoryCommit.Committer(
                    "login1",
                    1,
                    "node_id1",
                    "avatar_url1",
                    "",
                    "url1",
                    "html_url1",
                    "followers_url1",
                    "following_url1",
                    "gits_url1",
                    "starred_url1",
                    "subscriptions_url1",
                    "organizations_url1",
                    "repos_url1",
                    "events_url1",
                    "received_url1",
                    "type1",
                    false
                ),
                arrayListOf(RepositoryCommit.Parents(
                    "123456789qwerty123456789qwerty1234567890",
                    "url1",
                    "html_url1"
                ))
            ),
            RepositoryCommit(
                "123456789qwerty123456789qwerty1234567890",
                "node_id2",
                RepositoryCommit.Commit(
                    RepositoryCommit.Commit.Author(
                        "name2",
                        "email2",
                        "date2"
                    ),
                    RepositoryCommit.Commit.Author(
                        "name2",
                        "email2",
                        "date2"
                    ),
                    "message2",
                    RepositoryCommit.Commit.Tree(
                        "123456789qwerty123456789qwerty1234567890",
                        "url2"
                    ),
                    "url2",
                    2,
                    RepositoryCommit.Commit.Verification(
                        false,
                        "unsigned",
                        null,
                        null
                    )
                ),
                "url2",
                "html_url2",
                "comments_url2",
                RepositoryCommit.Committer(
                    "login2",
                    2,
                    "node_id2",
                    "avatar_url2",
                    "",
                    "url2",
                    "html_url2",
                    "followers_url2",
                    "following_url2",
                    "gits_url2",
                    "starred_url2",
                    "subscriptions_url2",
                    "organizations_url2",
                    "repos_url2",
                    "events_url2",
                    "received_url2",
                    "type2",
                    false
                ),
                RepositoryCommit.Committer(
                    "login2",
                    2,
                    "node_id2",
                    "avatar_url2",
                    "",
                    "url2",
                    "html_url2",
                    "followers_url2",
                    "following_url2",
                    "gits_url2",
                    "starred_url2",
                    "subscriptions_url2",
                    "organizations_url2",
                    "repos_url2",
                    "events_url2",
                    "received_url2",
                    "type2",
                    false
                ),
                arrayListOf(RepositoryCommit.Parents(
                    "123456789qwerty123456789qwerty1234567890",
                    "url2",
                    "html_url2"
                ))
            )
        )
    }

    fun getRepositoryCommitEntities(): ArrayList<RepositoryCommitEntity> {
        return arrayListOf(
            RepositoryCommitEntity(
                "message1",
                "date1",
                "123456789qwerty123456789qwerty1234567890",
                RepositoryCommit.Committer(
                    "login1",
                    1,
                    "node_id1",
                    "avatar_url1",
                    "",
                    "url1",
                    "html_url1",
                    "followers_url1",
                    "following_url1",
                    "gits_url1",
                    "starred_url1",
                    "subscriptions_url1",
                    "organizations_url1",
                    "repos_url1",
                    "events_url1",
                    "received_url1",
                    "type1",
                    false
                ),
                RepositoryCommit.Commit(
                    RepositoryCommit.Commit.Author(
                        "name1",
                        "email1",
                        "date1"
                    ),
                    RepositoryCommit.Commit.Author(
                        "name1",
                        "email1",
                        "date1"
                    ),
                    "message1",
                    RepositoryCommit.Commit.Tree(
                        "123456789qwerty123456789qwerty1234567890",
                        "url1"
                    ),
                    "url1",
                    1,
                    RepositoryCommit.Commit.Verification(
                        false,
                        "unsigned",
                        null,
                        null
                    )
                )
            ),
            RepositoryCommitEntity(
                "message2",
                "date2",
                "123456789qwerty123456789qwerty1234567890",
                RepositoryCommit.Committer(
                    "login2",
                    2,
                    "node_id2",
                    "avatar_url2",
                    "",
                    "url2",
                    "html_url2",
                    "followers_url2",
                    "following_url2",
                    "gits_url2",
                    "starred_url2",
                    "subscriptions_url2",
                    "organizations_url2",
                    "repos_url2",
                    "events_url2",
                    "received_url2",
                    "type2",
                    false
                ),
                RepositoryCommit.Commit(
                    RepositoryCommit.Commit.Author(
                        "name2",
                        "email2",
                        "date2"
                    ),
                    RepositoryCommit.Commit.Author(
                        "name2",
                        "email2",
                        "date2"
                    ),
                    "message2",
                    RepositoryCommit.Commit.Tree(
                        "123456789qwerty123456789qwerty1234567890",
                        "url2"
                    ),
                    "url2",
                    2,
                    RepositoryCommit.Commit.Verification(
                        false,
                        "unsigned",
                        null,
                        null
                    )
                )
            )
        )
    }

    fun getRepositoryCommitsUI(): ArrayList<RepositoryCommitUI> {
        return arrayListOf(
            RepositoryCommitUI(
                "message1",
                "date1",
                "123456789qwerty123456789qwerty1234567890",
                "avatar_url1",
                "login1"
            ),
            RepositoryCommitUI(
                "message2",
                "date2",
                "123456789qwerty123456789qwerty1234567890",
                "avatar_url2",
                "login2"
            )
        )
    }
}